### ISSUE TITLE
Error when build an app with Meteor 0.6.5

### ISSUE THREAD

**Issue by artpolikarpov** [jordansissel/heroku-buildpack-meteor#17]
Heroku logs:

```bash
2013-08-15T12:06:29+00:00 heroku[slug-compiler]: Slug compilation started
2013-08-15T12:06:43.647196+00:00 heroku[api]: Deploy 213bfc9 by artpolikarpov@getwear.com
2013-08-15T12:06:43.671450+00:00 heroku[api]: Release v350 created by artpolikarpov@getwear.com
2013-08-15T12:06:43.777150+00:00 heroku[web.1]: State changed from down to starting
2013-08-15T12:06:44+00:00 heroku[slug-compiler]: Slug compilation finished
2013-08-15T12:06:46.259053+00:00 heroku[web.1]: Starting process with command `PATH=.meteor/local/usr/bin:.meteor/local/usr/lib/meteor/bin:bin:/usr/local/bin:/usr/bin:/bin NODE_PATH=.meteor/local/usr/lib/meteor/lib/node_modules MONGO_URL=mongodb://heroku:c2130dda19da2b5a60ffae67ce4134a5@dharma.mongohq.com:10026/app14902610 .meteor/local/usr/lib/meteor/bin/node .meteor/local/build/main.js`
2013-08-15T12:06:46.926998+00:00 app[web.1]: module.js:340
2013-08-15T12:06:46.930406+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2013-08-15T12:06:46.926865+00:00 app[web.1]: 
2013-08-15T12:06:46.927270+00:00 app[web.1]:     throw err;
2013-08-15T12:06:46.927270+00:00 app[web.1]:           ^
2013-08-15T12:06:46.930406+00:00 app[web.1]: Error: Cannot find module '/app/.meteor/local/build/main.js'
2013-08-15T12:06:46.930406+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2013-08-15T12:06:46.930406+00:00 app[web.1]:     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
2013-08-15T12:06:46.930406+00:00 app[web.1]:     at Module.runMain (module.js:492:10)
2013-08-15T12:06:48.127332+00:00 heroku[web.1]: Process exited with status 1
```

Can you help?

**Comment by wfleming** [comment]
Outdated: buildpack has now been updated for newer Meteors.
