### ISSUE TITLE
Gettin auth failed error

### ISSUE THREAD

**Issue by estock** [jordansissel/heroku-buildpack-meteor#38]
I tried to deploy my app but having issues I configured the username and password using mongolabs, but when I try to run my app I'm running into an issue. it says

Exception in callback of async function: MongoError: auth failed

I'm running the same version of mongo locally, so i know it's not that, and i tripple checked the passwords ,and tried it via command line and it seems to work

**Comment by thomasvanlankveld** [comment]
Same here

``` shell
2016-01-08T16:38:11.770833+00:00 heroku[web.1]: State changed from crashed to starting
2016-01-08T16:38:27.400686+00:00 heroku[web.1]: Starting process with command `node build/bundle/main.js`
2016-01-08T16:38:30.070246+00:00 app[web.1]: Exception in callback of async function: MongoError: auth failed
2016-01-08T16:38:30.070267+00:00 app[web.1]:     at [object Object].emit (events.js:98:17)
2016-01-08T16:38:30.070257+00:00 app[web.1]:     at Object.toError (/app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11)
2016-01-08T16:38:30.070259+00:00 app[web.1]:     at /app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1128:31
2016-01-08T16:38:30.070260+00:00 app[web.1]:     at /app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1843:9
2016-01-08T16:38:30.070261+00:00 app[web.1]:     at Server.Base._callHandler (/app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
2016-01-08T16:38:30.070261+00:00 app[web.1]:     at /app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
2016-01-08T16:38:30.070264+00:00 app[web.1]:     at [object Object].MongoReply.parseBody (/app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
2016-01-08T16:38:30.070264+00:00 app[web.1]:     at [object Object].<anonymous> (/app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
2016-01-08T16:38:30.070265+00:00 app[web.1]:     at [object Object].emit (events.js:95:17)
2016-01-08T16:38:30.070266+00:00 app[web.1]:     at [object Object].<anonymous> (/app/build/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
2016-01-08T16:38:36.602197+00:00 heroku[web.1]: State changed from crashed to starting
2016-01-08T16:39:27.553585+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-01-08T16:39:27.553585+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-01-08T16:39:28.233945+00:00 heroku[web.1]: Process exited with status 137
2016-01-08T16:39:28.234555+00:00 heroku[web.1]: State changed from starting to crashed
```

Config var is set to `mongodb://<username>:<password>@ds035995.mongolab.com:35995/<database>`, but I can connect with `mongo -u <username> -p <password> ds035995.mongolab.com:35995/<database>`

_update:_

Checking if this is a problem has to do with my Meteor version, `1.0.3.1`. Going to try again after updating to `1.2.1`.

_update:_

Updating Meteor from `1.0.3.1` to `1.2.1` solved the problem for me.
