### ISSUE TITLE
undefined method `netrc_filename' for Netrc:Class

### ISSUE THREAD

**Issue by evjan** [jordansissel/heroku-buildpack-meteor#43]
When running `heroku create --buildpack https://github.com/jordansissel/heroku-buildpack-meteor.git` I get the following error on OS X:

```
undefined method `netrc_filename' for Netrc:Class
/usr/local/heroku/lib/heroku/auth.rb:138:in `netrc_path'
/usr/local/heroku/lib/heroku/auth.rb:160:in `rescue in netrc'
/usr/local/heroku/lib/heroku/auth.rb:151:in `netrc'
/usr/local/heroku/lib/heroku/auth.rb:178:in `read_credentials'
/usr/local/heroku/lib/heroku/auth.rb:113:in `get_credentials'
/usr/local/heroku/lib/heroku/auth.rb:89:in `password'
/usr/local/heroku/lib/heroku/auth.rb:17:in `api'
/usr/local/heroku/lib/heroku/command/base.rb:72:in `api'
/usr/local/heroku/lib/heroku/command/apps.rb:131:in `create'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/local/bin/heroku:24:in `<main>'

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `netrc_filename' for Netrc:Class (NoMethodError)
    Command:     heroku create --buildpack https://github.com/jordansissel/heroku-buildpack-meteor.git
    Plugins:     heroku-deploy
                 heroku-exit-status

    Version:     heroku-toolbelt/3.42.24 (x86_64-darwin10.8.0) ruby/1.9.3


    More information in /Users/[username]/.heroku/error.log
```

Output from `heroku version`:

```
heroku-toolbelt/3.42.24 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.27.8-2294739 (amd64-darwin) go1.5.1
=== Installed Plugins
heroku-apps@1.0.0
heroku-cli-addons@0.1.1
heroku-deploy
heroku-exit-status
heroku-fork@4.0.0
heroku-git@2.4.4
heroku-local@4.1.5
heroku-run@2.9.2
heroku-status@1.2.3
```

**Comment by keithpitty** [comment]
@evjan I was seeing the same issue. To resolve it I had to uninstall the heroku toolbelt and then reinstall it.
