### ISSUE TITLE
App works locally but crashes on Heroku?

### ISSUE THREAD

**Issue by Broham** [jordansissel/heroku-buildpack-meteor#68]
I followed the steps in t[his stackoverflow question](http://stackoverflow.com/questions/23056162/where-to-host-meteor-apps), but for some reason the app crashes on heroku even though it works on my local machine.  I checked the logs and found this information:

```
2016-09-20T19:28:18.096258+00:00 heroku[web.1]: State changed from crashed to starting
2016-09-20T19:28:39.792352+00:00 heroku[web.1]: Starting process with command `node build/bundle/main.js`
2016-09-20T19:28:44.018244+00:00 app[web.1]: 
2016-09-20T19:28:44.018578+00:00 app[web.1]: assert.js:93
2016-09-20T19:28:44.018940+00:00 app[web.1]:   throw new assert.AssertionError({
2016-09-20T19:28:44.018944+00:00 app[web.1]:         ^
2016-09-20T19:28:44.021453+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-09-20T19:28:44.021455+00:00 app[web.1]:     at wrapPathFunction (/app/build/bundle/programs/server/mini-files.js:77:10)
2016-09-20T19:28:44.021456+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/mini-files.js:108:24)
2016-09-20T19:28:44.021456+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-09-20T19:28:44.021457+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-09-20T19:28:44.021458+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-09-20T19:28:44.021459+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-09-20T19:28:44.021459+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-09-20T19:28:44.021460+00:00 app[web.1]:     at require (module.js:380:17)
2016-09-20T19:28:44.021461+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2016-09-20T19:28:44.021461+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-09-20T19:28:44.174809+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-20T19:28:44.137122+00:00 heroku[web.1]: Process exited with status 8
```

Any idea why this might be happening or how I can fix it?

**Comment by rahulserver** [comment]
@Broham I too am facing the same issue. I would assume that this build pack would not work with meteor 1.4.x

Seems this needs to be fixed asap.

**Comment by maxko87** [comment]
Same issue.

**Comment by frayeralex** [comment]
i have same problem

**Comment by ickyrr** [comment]
this buildpack is not being updated anymore, i guess.. The version of node is still on v0.10.x, meteor is already using 4.5.0 version of node. I've made a guide for this, [here](https://meteorcoder.wordpress.com/2016/09/24/how-to-deploy-meteor-apps-with-heroku/). The buildpack I've used there is a fork of this [buildpack](https://www.google.com.ph/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi2irDZ3qzPAhUIFZQKHScfB04QFggaMAA&url=https%3A%2F%2Fgithub.com%2FAdmitHub%2Fmeteor-buildpack-horse&usg=AFQjCNH8fags7MlvP677JsX8Fb4ZnoObvA&sig2=02mS7-mY0cEX64EM6MpBXQ&bvm=bv.133700528,d.dGo).

**Comment by vlasov01** [comment]
@ickyrr Thank you for the workaround! It works for me.

**Comment by vlasov01** [comment]
@ickyrr Thank you for the workaround! It works for me.

**Comment by Luis16287** [comment]
@ickyrr could you give me access to your page?

**Comment by NagaSai6** [comment]
Same problem
